### ISSUE TITLE
Many sensors are not available anymore

### ISSUE THREAD

**Issue by Albert994** [BenPru/luxtronik#103]
I updated from 2022.12.22 to current version 2023.03.24.
Unfortunately many sensors (~30) are not available anymore e.g.:
sensor.luxtronik2_outdoor_temperature_average
sensor.luxtronik2_compressor_heating_temperature
sensor.luxtronik2_pump_frequency
sensor.luxtronik2_compressor_impulses
sensor.luxtronik2_domenstic_water_temperature
sensor.luxtronik2_heat_source_input_temperature

In Jan, there was a similar issues reported #79, but this is closed as solved.

**Comment by BenPru** [comment]
Should be fixed with the pre-release [2023.9.10](https://github.com/BenPru/luxtronik/releases/tag/2023.9.10)
Thanks four your support.

**Comment by Albert994** [comment]
@BenPru: I updated to this version, unfortunately the sensors are still not available.

**Comment by Albert994** [comment]
I saw in the log the following error:

Logger: homeassistant.components.sensor
Source: custom_components/luxtronik2/sensor.py:1206
Integration: Sensor (documentation, issues)
First occurred: 19:18:25 (1 occurrences)
Last logged: 19:18:25

Error while setting up luxtronik2 platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 362, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/luxtronik2/sensor.py", line 531, in async_setup_entry
    add_sensor_if_active(luxtronik, entities, "visibilities.ID_Visi_Waermemenge_ZWE", LuxtronikSensor(
  File "/config/custom_components/luxtronik2/sensor.py", line 1206, in add_sensor_if_active
    if luxtronik.get_value(check_key) <= 0:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '<=' not supported between instances of 'NoneType' and 'int'


I commented out 2 lines in sensor.py:
def add_sensor_if_active(luxtronik, entities, check_key: str, sensor: LuxtronikSensor):
#    if luxtronik.get_value(check_key) <= 0:
#        sensor.disable_by_default()
    entities += [sensor]

No most of the sensors are back again. Only 4 are still missing

**Comment by BenPru** [comment]
Please try the current main branch.

**Comment by miktin** [comment]
Same hear

**Comment by BenPru** [comment]
@miktin and @Albert994 Please create a diagnostic file and provide it as attachment.
![image](https://github.com/BenPru/luxtronik/assets/32298537/954d38c4-8ca7-47f6-baaa-e539372d6e7b)

**Comment by miktin** [comment]
It works many month. After last update from HA have this problems.
