### ISSUE TITLE
2023.9.21-Alpha-Core-Preview some issue with HA API

### ISSUE THREAD

**Issue by ondras76** [BenPru/luxtronik#142]
I was updatet HA Core to 2023.9.2, all working fine except Luxtronik. So I was update Luxtronik to version 2023.9.21-Alpha-Core-Preview.
Everything looks OK just menu HA Cloud loading and loading ... and doesn't work. In log can see some problem with API. I don't know if is the problem, but is only issue in log file.

"Logger: homeassistant.components.websocket_api.http.connection
Source: components/cloud/google_config.py:153
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 12:30:48 PM (8 occurrences)
Last logged: 12:40:08 PM

[139884542836160] Error handling message: Unknown error (unknown_error) Ondrej from 10.0.0.130 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36)
[139883500892096] Error handling message: Unknown error (unknown_error) Ondrej from 10.0.0.130 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 26, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/cloud/http_api.py", line 357, in websocket_cloud_status
    websocket_api.result_message(msg["id"], await _account_data(hass, cloud))
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/cloud/http_api.py", line 525, in _account_data
    google_config = await client.get_google_config()
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/cloud/client.py", line 133, in get_google_config
    await google_conf.async_initialize()
  File "/usr/src/homeassistant/homeassistant/components/cloud/google_config.py", line 212, in async_initialize
    await super().async_initialize()
  File "/usr/src/homeassistant/homeassistant/components/google_assistant/helpers.py", line 106, in async_initialize
    if not self.enabled:
           ^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/cloud/google_config.py", line 153, in enabled
    and not self._cloud.subscription_expired
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/hass_nabucasa/__init__.py", line 133, in subscription_expired
    return utcnow() > self.expiration_date + timedelta(days=7)
                      ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/hass_nabucasa/__init__.py", line 139, in expiration_date
    raise ValueError(
ValueError: Invalid expiration date (2024-08-21)
"

**Comment by BenPru** [comment]
HA Cloud and the log entries have nothing to do with the Luxtronik integration.

**Comment by ondras76** [comment]
I don't know, but it happend. I was try 2x, Always after Luxtronik update.

**Comment by ondras76** [comment]
@BenPru  please can you look on my log file. I was deleted the Luxtronik integration, last Core update ans all working fine. So I was download againg Luxtronik via HACS and when I connect the HUB the cloud is gone. At 13:17 I was run the HUB. It's realy something with Luxtronik.
"Home Assistant Core
[139695334792384] Error handling message: Unknown error (unknown_error) Ondrej from 10.0.0.130 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36)
1:17:49 PM – (ERROR) Home Assistant WebSocket API - message first occurred at 1:17:41 PM and shows up 2 times
Function get_sensor_data luxtronik_key UNSET is None
1:17:37 PM – (WARNING) Luxtronik (custom integration) - message first occurred at 1:17:17 PM and shows up 4 times
Error doing job: Exception in callback CloudGoogleConfig._handle_entity_registry_updated(<Event entity...ing_threshold>)
1:17:24 PM – (ERROR) components/cloud/google_config.py - message first occurred at 1:17:16 PM and shows up 163 times
Error doing job: Task exception was never retrieved
1:17:17 PM – (ERROR) components/cloud/alexa_config.py - message first occurred at 1:17:17 PM and shows up 158 times
Get_device_entity_title key climate.cooling not found in
1:17:16 PM – (WARNING) Luxtronik (custom integration)
Template variable error: 'None' has no attribute 'last_changed' when rendering '{% if is_state("sensor.luxtronik2_outdoor_temperature", 'unknown') %} unknown {% else %} {% if states('sensor.luxtronik2_outdoor_temperature') == states('sensor.luxtronik2_outdoor_temperature', true) %} {{ 'ON' if now().timestamp() - states.sensor.luxtronik2_outdoor_temperature.last_changed.timestamp() > 300 else 'OFF' }} {% else %} {{ 'ON' if states.sensor.luxtronik2_outdoor_temperature.state == 'unknown' else 'OFF' }} {% endif %} {% endif %}'
1:17:00 PM – (ERROR) helpers/template.py - message first occurred at 12:20:00 PM and shows up 58 times"

[home-assistant_2023-09-24T11-18-57.919Z.log](https://github.com/BenPru/luxtronik/files/12708377/home-assistant_2023-09-24T11-18-57.919Z.log)

**Comment by BenPru** [comment]
You get only template errors. Please read the release notes. Some keys have changed.
I think you are using outdated keys in your templates.

**Comment by ondras76** [comment]
hi, I was try meke on my second machine rpi, make clean HA instalation with just Luxtronik and the problem is the same with cloud.

**Comment by AJediIAm** [comment]
I had a similar issue which caused the nabu Casa cloud to malfunction: https://github.com/home-assistant/core/issues/100564
Disabling/enabling the Luxtronik2 integration confirmed my could issue is related to Luxtronik2.

I disabled the integration for a while since I assumed it was something unique to my setup.
When I noticed this issue, I checked again with the latest version of the integration and my error now matches the one reported by @ondras76.

Nabu Casa cloud seems to be stable for now, but my Netatmo integration fails to load when Luxtronik2 is enabled

**Comment by ondras76** [comment]
On clean instalation with only Luxtronik, without connected cloud I see the internal HA weather forecast Meteorologisk institutt can't connect.

**Comment by AJediIAm** [comment]
I have a WZSV 62 K3M which is identified as MSW2-6S in the software.
It is a water/water heatpump with cooling and DHW.
If we find commonalities with heatspumps which either have or dont have the same issue, we might get clues about the code which causes this. 

@BenPru what kind of heatpump do you have? 
What kind of logs would be interesting to look at?

@BenPru if you want, I can setup a development instance for you and give you access for testing. This offer extends beyond this specific issue.

**Comment by ondras76** [comment]
My heat pump is, Alpha Innotec LWDW 9, with luxtronik regulator.

**Comment by BenPru** [comment]
> [home-assistant_2023-09-24T12-25-44.524Z.log](https://github.com/BenPru/luxtronik/files/12708483/home-assistant_2023-09-24T12-25-44.524Z.log)

You use the states object direkt: 'states.*' - e.g. states.sensor.luxtronik2_outdoor_temperature.state.
This is not best practice and cause errors. See the [docs](https://www.home-assistant.io/integrations/template/#startup).

**Comment by ondras76** [comment]
@BenPru thank you for your comment, propably you right, but like I said today. I was try new instaltion on my second machine, just clean Haos and Luxtronik, the issue is the same. When I connect the Luxtronik hub something happend and cloud can't connect. Also if I have cloud off, some integrations like a internal Meteo.. forecast can't connect. Thank you for your help.

**Comment by BenPru** [comment]
If the integration can not connect to the heatpump on the network layer an exception is thrown. It is possible that this exception has an impact for ha and other integrations.
In the next days I try to have a look to handle this socket error graceful.
But have you checked your config? Have you the same error in the log in your test env?

**Comment by BenPru** [comment]
> @BenPru what kind of heatpump do you have? What kind of logs would be interesting to look at?

Novelan LAD 7 with V2.88.1 (V2.88.3 available)
Errors abount luxtronik. (Not from template vars!)

> @BenPru if you want, I can setup a development instance for you and give you access for testing. This offer extends beyond this specific issue.

Sorry, I don't have the time to debug remote.

**Comment by ondras76** [comment]
> If the integration can not connect to the heatpump on the network layer an exception is thrown. It is possible that this exception has an impact for ha and other integrations. In older ha versions this was a problem. But normally ha should handle integration errors. Perhaps this is a new problem in 2023.9.2 and higher.
> 
> It is also possible that the startup order in ha 2023.9.2.>= has changed and it has an impact that template sensors grab values from the luxtronik integration. If one template uses "states,*" it could crash ha. I have the same in the past.
> 
> In the next days I try to have a look to handle this socket error graceful.
> 
> But have you checked your config? Have you the same error in the log in your test env?
Like I said, it's clean install. I didn't make any changes in config. This is only issue afrer starting hub luxtronik.

![image](https://github.com/BenPru/luxtronik/assets/115325615/47a08db5-df1d-4fcc-beb5-9539b2a268e1)
![image](https://github.com/BenPru/luxtronik/assets/115325615/d3e16f9b-693c-49d0-b3a9-15eb0a1f0f90)
![image](https://github.com/BenPru/luxtronik/assets/115325615/8874fbc6-ea7b-47f0-8d61-95078c51127d)

**Comment by BenPru** [comment]
> .. Like I said, it's clean install. I didn't make any changes in config. This is only issue afrer starting hub luxtronik.

Clean install with only installed but not configured luxtronik integration?
And no luxtronik error in the log?

**Comment by ondras76** [comment]
> > .. Like I said, it's clean install. I didn't make any changes in config. This is only issue afrer starting hub luxtronik.
> 
> 
> 
> Clean install with only installed but not configured luxtronik integration?
> 
> And no luxtronik error in the log?


No any errors without Luxtronik.

**Comment by BenPru** [comment]
If an integration is not configured HA should not load and use this integration.
You get an error without integration configuration, so HA have a big change in the integration handling. But in the ha dev blog nothing was communicated...
I try to provide a hotfix in the main branch. Please try this one.

**Comment by ondras76** [comment]
> If an integration is not configured HA should not load and use this integration. You get an error without integration configuration, so HA have a big change in the integration handling. But in the ha dev blog nothing was communicated... I try to provide a hotfix in the main branch. Please try this one.

sorry was also this when the Luxtronik running
![Screenshot 2023-10-01 233531](https://github.com/BenPru/luxtronik/assets/115325615/3f06000f-8f08-4908-af2f-aa4531f82ab3)

**Comment by ondras76** [comment]
> If an integration is not configured HA should not load and use this integration.
> 
> You get an error without integration configuration, so HA have a big change in the integration handling. But in the ha dev blog nothing was communicated...
> 
> I try to provide a hotfix in the main branch. Please try this one.



I don't any problem when the integration not configured, the problem is only when IS configured.

**Comment by idominiki** [comment]
Same problem here

**Comment by idominiki** [comment]
Any news regarding a functional version for HA 2023.10? 

I tested both alpha version and main brunch. Installation of the integration is no problem. If I want to configure the heatpump (Alpha innotec SWCV) I got a timeout, than ha restarts and nothing happened. 

Heating season is before and I want to track my energy. 

Thanks!

**Comment by BenPru** [comment]
> Any news regarding a functional version for HA 2023.10? 

No, I have no news. But thanks for your input. I try to reconf my test env.
I have tried to activate every optional entity but all works fine in my envs... I can't produce any error.
Do you have something in your logs?

**Comment by idominiki** [comment]
> > Any news regarding a functional version for HA 2023.10? 
> 
> No, I have no news. But thanks for your input. I try to reconf my test env.
> I have tried to activate every optional entity but all works fine in my envs... I can't produce any error.
> Do you have something in your logs?

As home assistant is restarting immediately after configuration I will try to catch logs tomorrow.

**Comment by idominiki** [comment]
> > Any news regarding a functional version for HA 2023.10? 
> 
> No, I have no news. But thanks for your input. I try to reconf my test env.
> I have tried to activate every optional entity but all works fine in my envs... I can't produce any error.
> Do you have something in your logs?

Should I test the main branch or the latest alpha release?

**Comment by idominiki** [comment]
This is the output from homeassistant.log while I want to configure the luxtronik host. 

`2023-10-08 17:12:31.999 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 227, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 31, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 148, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/http.py", line 50, in get
    return await WebSocketHandler(request.app["hass"], request).async_handle()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/http.py", line 276, in async_handle
    await wsock.prepare(request)
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_ws.py", line 138, in prepare
    payload_writer = await super().prepare(request)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_response.py", line 421, in prepare
    return await self._start(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_response.py", line 429, in _start
    await self._write_headers()
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_response.py", line 502, in _write_headers
    await writer.write_headers(status_line, self._headers)
  File "/usr/local/lib/python3.11/site-packages/aiohttp/http_writer.py", line 130, in write_headers
    self._write(buf)
  File "/usr/local/lib/python3.11/site-packages/aiohttp/http_writer.py", line 75, in _write
    raise ConnectionResetError("Cannot write to closing transport")
ConnectionResetError: Cannot write to closing transport
2023-10-08 17:12:32.018 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 227, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 31, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 148, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/http.py", line 50, in get
    return await WebSocketHandler(request.app["hass"], request).async_handle()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/http.py", line 276, in async_handle
    await wsock.prepare(request)
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_ws.py", line 138, in prepare
    payload_writer = await super().prepare(request)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_response.py", line 421, in prepare
    return await self._start(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_response.py", line 429, in _start
    await self._write_headers()
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_response.py", line 502, in _write_headers
    await writer.write_headers(status_line, self._headers)
  File "/usr/local/lib/python3.11/site-packages/aiohttp/http_writer.py", line 130, in write_headers
    self._write(buf)
  File "/usr/local/lib/python3.11/site-packages/aiohttp/http_writer.py", line 75, in _write
    raise ConnectionResetError("Cannot write to closing transport")
ConnectionResetError: Cannot write to closing transport
2023-10-08 17:12:32.025 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 227, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 31, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 148, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/http.py", line 50, in get
    return await WebSocketHandler(request.app["hass"], request).async_handle()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/http.py", line 276, in async_handle
    await wsock.prepare(request)
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_ws.py", line 138, in prepare
    payload_writer = await super().prepare(request)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_response.py", line 421, in prepare
    return await self._start(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_response.py", line 429, in _start
    await self._write_headers()
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_response.py", line 502, in _write_headers
    await writer.write_headers(status_line, self._headers)
  File "/usr/local/lib/python3.11/site-packages/aiohttp/http_writer.py", line 130, in write_headers
    self._write(buf)
  File "/usr/local/lib/python3.11/site-packages/aiohttp/http_writer.py", line 75, in _write
    raise ConnectionResetError("Cannot write to closing transport")
ConnectionResetError: Cannot write to closing transport
2023-10-08 17:12:32.030 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 227, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 31, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 148, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/http.py", line 50, in get
    return await WebSocketHandler(request.app["hass"], request).async_handle()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/http.py", line 276, in async_handle
    await wsock.prepare(request)
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_ws.py", line 138, in prepare
    payload_writer = await super().prepare(request)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_response.py", line 421, in prepare
    return await self._start(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_response.py", line 429, in _start
    await self._write_headers()
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_response.py", line 502, in _write_headers
    await writer.write_headers(status_line, self._headers)
  File "/usr/local/lib/python3.11/site-packages/aiohttp/http_writer.py", line 130, in write_headers
    self._write(buf)
  File "/usr/local/lib/python3.11/site-packages/aiohttp/http_writer.py", line 75, in _write
    raise ConnectionResetError("Cannot write to closing transport")
ConnectionResetError: Cannot write to closing transport
2023-10-08 17:12:32.046 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 227, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 31, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 148, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/http.py", line 50, in get
    return await WebSocketHandler(request.app["hass"], request).async_handle()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/http.py", line 276, in async_handle
    await wsock.prepare(request)
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_ws.py", line 138, in prepare
    payload_writer = await super().prepare(request)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_response.py", line 421, in prepare
    return await self._start(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_response.py", line 429, in _start
    await self._write_headers()
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_response.py", line 502, in _write_headers
    await writer.write_headers(status_line, self._headers)
  File "/usr/local/lib/python3.11/site-packages/aiohttp/http_writer.py", line 130, in write_headers
    self._write(buf)
  File "/usr/local/lib/python3.11/site-packages/aiohttp/http_writer.py", line 75, in _write
    raise ConnectionResetError("Cannot write to closing transport")
ConnectionResetError: Cannot write to closing transport
2023-10-08 17:12:43.312 ERROR (MainThread) [aiohomekit.controller.coap.connection] Decryption failed, desynchronized? Counter=239/240
2023-10-08 17:12:43.312 ERROR (MainThread) [aiohomekit.controller.coap.connection] Failed flailing attempts to resynchronize, self-destructing in 3, 2, 1...
`

The problem is, as soon as I send the IP and Port, home assistant closing its connection. Hangs up for 5 minutes and restart.

This is the supervisor log output:
![Bildschirmfoto 2023-10-08 um 17 10 24](https://github.com/BenPru/luxtronik/assets/62521486/7a15e144-2452-4822-849f-11eb762b8e22)

**Comment by ondras76** [comment]
> This is the output from homeassistant.log while I want to configure the luxtronik host. 
> 
> 
> 
> `2023-10-08 17:12:31.999 ERROR (MainThread) [aiohttp.server] Error handling request
> 
> Traceback (most recent call last):
> 
>   File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
> 
>     resp = await request_handler(request)
> 
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "/usr/local/lib/python3.11/site-packages/aiohttp/web_app.py", line 504, in _handle
> 
>     resp = await handler(request)
> 
>            ^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "/usr/local/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 117, in impl
> 
>     return await handler(request)
> 
>            ^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware
> 
>     return await handler(request)
> 
>            ^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 227, in forwarded_middleware
> 
>     return await handler(request)
> 
>            ^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
> 
>     return await handler(request)
> 
>            ^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
> 
>     return await handler(request)
> 
>            ^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
> 
>     return await handler(request)
> 
>            ^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 31, in headers_middleware
> 
>     response = await handler(request)
> 
>                ^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 148, in handle
> 
>     result = await handler(request, **request.match_info)
> 
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "/usr/src/homeassistant/homeassistant/components/websocket_api/http.py", line 50, in get
> 
>     return await WebSocketHandler(request.app["hass"], request).async_handle()
> 
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "/usr/src/homeassistant/homeassistant/components/websocket_api/http.py", line 276, in async_handle
> 
>     await wsock.prepare(request)
> 
>   File "/usr/local/lib/python3.11/site-packages/aiohttp/web_ws.py", line 138, in prepare
> 
>     payload_writer = await super().prepare(request)
> 
>                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "/usr/local/lib/python3.11/site-packages/aiohttp/web_response.py", line 421, in prepare
> 
>     return await self._start(request)
> 
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "/usr/local/lib/python3.11/site-packages/aiohttp/web_response.py", line 429, in _start
> 
>     await self._write_headers()
> 
>   File "/usr/local/lib/python3.11/site-packages/aiohttp/web_response.py", line 502, in _write_headers
> 
>     await writer.write_headers(status_line, self._headers)
> 
>   File "/usr/local/lib/python3.11/site-packages/aiohttp/http_writer.py", line 130, in write_headers
> 
>     self._write(buf)
> 
>   File "/usr/local/lib/python3.11/site-packages/aiohttp/http_writer.py", line 75, in _write
> 
>     raise ConnectionResetError("Cannot write to closing transport")
> 
> ConnectionResetError: Cannot write to closing transport
> 
> 2023-10-08 17:12:32.018 ERROR (MainThread) [aiohttp.server] Error handling request
> 
> Traceback (most recent call last):
> 
>   File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
> 
>     resp = await request_handler(request)
> 
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "/usr/local/lib/python3.11/site-packages/aiohttp/web_app.py", line 504, in _handle
> 
>     resp = await handler(request)
> 
>            ^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "/usr/local/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 117, in impl
> 
>     return await handler(request)
> 
>            ^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware
> 
>     return await handler(request)
> 
>            ^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 227, in forwarded_middleware
> 
>     return await handler(request)
> 
>            ^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
> 
>     return await handler(request)
> 
>            ^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
> 
>     return await handler(request)
> 
>            ^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
> 
>     return await handler(request)
> 
>            ^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 31, in headers_middleware
> 
>     response = await handler(request)
> 
>                ^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 148, in handle
> 
>     result = await handler(request, **request.match_info)
> 
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "/usr/src/homeassistant/homeassistant/components/websocket_api/http.py", line 50, in get
> 
>     return await WebSocketHandler(request.app["hass"], request).async_handle()
> 
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "/usr/src/homeassistant/homeassistant/components/websocket_api/http.py", line 276, in async_handle
> 
>     await wsock.prepare(request)
> 
>   File "/usr/local/lib/python3.11/site-packages/aiohttp/web_ws.py", line 138, in prepare
> 
>     payload_writer = await super().prepare(request)
> 
>                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "/usr/local/lib/python3.11/site-packages/aiohttp/web_response.py", line 421, in prepare
> 
>     return await self._start(request)
> 
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "/usr/local/lib/python3.11/site-packages/aiohttp/web_response.py", line 429, in _start
> 
>     await self._write_headers()
> 
>   File "/usr/local/lib/python3.11/site-packages/aiohttp/web_response.py", line 502, in _write_headers
> 
>     await writer.write_headers(status_line, self._headers)
> 
>   File "/usr/local/lib/python3.11/site-packages/aiohttp/http_writer.py", line 130, in write_headers
> 
>     self._write(buf)
> 
>   File "/usr/local/lib/python3.11/site-packages/aiohttp/http_writer.py", line 75, in _write
> 
>     raise ConnectionResetError("Cannot write to closing transport")
> 
> ConnectionResetError: Cannot write to closing transport
> 
> 2023-10-08 17:12:32.025 ERROR (MainThread) [aiohttp.server] Error handling request
> 
> Traceback (most recent call last):
> 
>   File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
> 
>     resp = await request_handler(request)
> 
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "/usr/local/lib/python3.11/site-packages/aiohttp/web_app.py", line 504, in _handle
> 
>     resp = await handler(request)
> 
>            ^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "/usr/local/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 117, in impl
> 
>     return await handler(request)
> 
>            ^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware
> 
>     return await handler(request)
> 
>            ^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 227, in forwarded_middleware
> 
>     return await handler(request)
> 
>            ^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
> 
>     return await handler(request)
> 
>            ^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
> 
>     return await handler(request)
> 
>            ^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
> 
>     return await handler(request)
> 
>            ^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 31, in headers_middleware
> 
>     response = await handler(request)
> 
>                ^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 148, in handle
> 
>     result = await handler(request, **request.match_info)
> 
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "/usr/src/homeassistant/homeassistant/components/websocket_api/http.py", line 50, in get
> 
>     return await WebSocketHandler(request.app["hass"], request).async_handle()
> 
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "/usr/src/homeassistant/homeassistant/components/websocket_api/http.py", line 276, in async_handle
> 
>     await wsock.prepare(request)
> 
>   File "/usr/local/lib/python3.11/site-packages/aiohttp/web_ws.py", line 138, in prepare
> 
>     payload_writer = await super().prepare(request)
> 
>                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "/usr/local/lib/python3.11/site-packages/aiohttp/web_response.py", line 421, in prepare
> 
>     return await self._start(request)
> 
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "/usr/local/lib/python3.11/site-packages/aiohttp/web_response.py", line 429, in _start
> 
>     await self._write_headers()
> 
>   File "/usr/local/lib/python3.11/site-packages/aiohttp/web_response.py", line 502, in _write_headers
> 
>     await writer.write_headers(status_line, self._headers)
> 
>   File "/usr/local/lib/python3.11/site-packages/aiohttp/http_writer.py", line 130, in write_headers
> 
>     self._write(buf)
> 
>   File "/usr/local/lib/python3.11/site-packages/aiohttp/http_writer.py", line 75, in _write
> 
>     raise ConnectionResetError("Cannot write to closing transport")
> 
> ConnectionResetError: Cannot write to closing transport
> 
> 2023-10-08 17:12:32.030 ERROR (MainThread) [aiohttp.server] Error handling request
> 
> Traceback (most recent call last):
> 
>   File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
> 
>     resp = await request_handler(request)
> 
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "/usr/local/lib/python3.11/site-packages/aiohttp/web_app.py", line 504, in _handle
> 
>     resp = await handler(request)
> 
>            ^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "/usr/local/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 117, in impl
> 
>     return await handler(request)
> 
>            ^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware
> 
>     return await handler(request)
> 
>            ^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 227, in forwarded_middleware
> 
>     return await handler(request)
> 
>            ^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
> 
>     return await handler(request)
> 
>            ^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
> 
>     return await handler(request)
> 
>            ^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
> 
>     return await handler(request)
> 
>            ^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 31, in headers_middleware
> 
>     response = await handler(request)
> 
>                ^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 148, in handle
> 
>     result = await handler(request, **request.match_info)
> 
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "/usr/src/homeassistant/homeassistant/components/websocket_api/http.py", line 50, in get
> 
>     return await WebSocketHandler(request.app["hass"], request).async_handle()
> 
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "/usr/src/homeassistant/homeassistant/components/websocket_api/http.py", line 276, in async_handle
> 
>     await wsock.prepare(request)
> 
>   File "/usr/local/lib/python3.11/site-packages/aiohttp/web_ws.py", line 138, in prepare
> 
>     payload_writer = await super().prepare(request)
> 
>                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "/usr/local/lib/python3.11/site-packages/aiohttp/web_response.py", line 421, in prepare
> 
>     return await self._start(request)
> 
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "/usr/local/lib/python3.11/site-packages/aiohttp/web_response.py", line 429, in _start
> 
>     await self._write_headers()
> 
>   File "/usr/local/lib/python3.11/site-packages/aiohttp/web_response.py", line 502, in _write_headers
> 
>     await writer.write_headers(status_line, self._headers)
> 
>   File "/usr/local/lib/python3.11/site-packages/aiohttp/http_writer.py", line 130, in write_headers
> 
>     self._write(buf)
> 
>   File "/usr/local/lib/python3.11/site-packages/aiohttp/http_writer.py", line 75, in _write
> 
>     raise ConnectionResetError("Cannot write to closing transport")
> 
> ConnectionResetError: Cannot write to closing transport
> 
> 2023-10-08 17:12:32.046 ERROR (MainThread) [aiohttp.server] Error handling request
> 
> Traceback (most recent call last):
> 
>   File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
> 
>     resp = await request_handler(request)
> 
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "/usr/local/lib/python3.11/site-packages/aiohttp/web_app.py", line 504, in _handle
> 
>     resp = await handler(request)
> 
>            ^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "/usr/local/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 117, in impl
> 
>     return await handler(request)
> 
>            ^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware
> 
>     return await handler(request)
> 
>            ^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 227, in forwarded_middleware
> 
>     return await handler(request)
> 
>            ^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
> 
>     return await handler(request)
> 
>            ^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
> 
>     return await handler(request)
> 
>            ^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
> 
>     return await handler(request)
> 
>            ^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 31, in headers_middleware
> 
>     response = await handler(request)
> 
>                ^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 148, in handle
> 
>     result = await handler(request, **request.match_info)
> 
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "/usr/src/homeassistant/homeassistant/components/websocket_api/http.py", line 50, in get
> 
>     return await WebSocketHandler(request.app["hass"], request).async_handle()
> 
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "/usr/src/homeassistant/homeassistant/components/websocket_api/http.py", line 276, in async_handle
> 
>     await wsock.prepare(request)
> 
>   File "/usr/local/lib/python3.11/site-packages/aiohttp/web_ws.py", line 138, in prepare
> 
>     payload_writer = await super().prepare(request)
> 
>                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "/usr/local/lib/python3.11/site-packages/aiohttp/web_response.py", line 421, in prepare
> 
>     return await self._start(request)
> 
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "/usr/local/lib/python3.11/site-packages/aiohttp/web_response.py", line 429, in _start
> 
>     await self._write_headers()
> 
>   File "/usr/local/lib/python3.11/site-packages/aiohttp/web_response.py", line 502, in _write_headers
> 
>     await writer.write_headers(status_line, self._headers)
> 
>   File "/usr/local/lib/python3.11/site-packages/aiohttp/http_writer.py", line 130, in write_headers
> 
>     self._write(buf)
> 
>   File "/usr/local/lib/python3.11/site-packages/aiohttp/http_writer.py", line 75, in _write
> 
>     raise ConnectionResetError("Cannot write to closing transport")
> 
> ConnectionResetError: Cannot write to closing transport
> 
> 2023-10-08 17:12:43.312 ERROR (MainThread) [aiohomekit.controller.coap.connection] Decryption failed, desynchronized? Counter=239/240
> 
> 2023-10-08 17:12:43.312 ERROR (MainThread) [aiohomekit.controller.coap.connection] Failed flailing attempts to resynchronize, self-destructing in 3, 2, 1...
> 
> `
> 
> 
> 
> The problem is, as soon as I send the IP and Port, home assistant closing its connection. Hangs up for 5 minutes and restart.
> 
> 
> 
> This is the supervisor log output:
> 
> ![Bildschirmfoto 2023-10-08 um 17 10 24](https://github.com/BenPru/luxtronik/assets/62521486/7a15e144-2452-4822-849f-11eb762b8e22)
> 
> 


- [ ] the same on my

**Comment by BenPru** [comment]
Please vote this comment:
👍🏽 I have this behavior and my heatpump has a cooling option
👎🏽 I have this behavior and my heatpump has NO cooling option

**Comment by BenPru** [comment]
Please try [2023.10.9-Alpha-Core-Preview](https://github.com/BenPru/luxtronik/releases/tag/2023.10.9-Alpha-Core-Preview)

**Comment by idominiki** [comment]
> Please try [2023.10.9-Alpha-Core-Preview](https://github.com/BenPru/luxtronik/releases/tag/2023.10.9-Alpha-Core-Preview)

Sadly same behavior for me. 

After I sent the form, ha doesn't respond anymore. 
![image](https://github.com/BenPru/luxtronik/assets/62521486/859b4624-7287-4dc3-bf5a-da7eeef18e6e)

**Comment by BenPru** [comment]
Please vote this comment:
👍🏽 I have this behavior and I **use** the Home Assistant Cloud from Nabu Casa
👎🏽 I have this behavior and I **don't use** the Home Assistant Cloud from Nabu Casa

**Comment by BenPru** [comment]
> Sadly same behavior for me.

Can you provide a current log as file attachment?

**Comment by idominiki** [comment]
> Now I'm totally confused...
> 
> > Sadly same behavior for me.
> 
> Can you provide a current log as file attachment?

Here is my latest homeassistant.log
[home-assistant.log](https://github.com/BenPru/luxtronik/files/12849548/home-assistant.log)

**Comment by BenPru** [comment]
Please, everbody who is involved with this issue, please check what you don't have an old yaml config with luxtronik2 sensors. If so please disable or delete the regarding yaml config lines.

Please vote this comment:
👍🏽 I have this behavior and I **have** template sensors using luxtronik sensors
👎🏽 I have this behavior and I **don't have** template sensors using luxtronik sensors

**Comment by idominiki** [comment]
I just removed all config lines regarding luxtronik2 sensor. 

Same behavior. Can't configure the integration.

**Comment by idominiki** [comment]
I GOT IT WORKING!!

Guys, please check your web server from your heat pump. My hangs up so I can't login remotely:
<img width="1510" alt="image" src="https://github.com/BenPru/luxtronik/assets/62521486/0f022a2d-6950-4233-8db3-836254710a79">

Restart your heat pump or re-enable DHCP in settings.

After the restart, I can setup the integration without any problems!

A big shout to @BenPru, sorry for the confusion but a big thanks for your support!!!

**Comment by ondras76** [comment]
> I GOT IT WORKING!!
> 
> 
> 
> Guys, please check your web server from your heat pump. My hangs up so I can't login remotely:
> 
> <img width="1510" alt="image" src="https://github.com/BenPru/luxtronik/assets/62521486/0f022a2d-6950-4233-8db3-836254710a79">
> 
> 
> 
> Restart your heat pump or re-enable DHCP in settings.
> 
> 
> 
> After the restart, I can setup the integration without any problems!
> 
> 
> 
> A big shout to @BenPru, sorry for the confusion but a big thanks for your support!!!

what web server you mean?

**Comment by idominiki** [comment]
> > I GOT IT WORKING!!
> > 
> > 
> > 
> > Guys, please check your web server from your heat pump. My hangs up so I can't login remotely:
> > 
> > <img width="1510" alt="image" src="https://github.com/BenPru/luxtronik/assets/62521486/0f022a2d-6950-4233-8db3-836254710a79">
> > 
> > 
> > 
> > Restart your heat pump or re-enable DHCP in settings.
> > 
> > 
> > 
> > After the restart, I can setup the integration without any problems!
> > 
> > 
> > 
> > A big shout to @BenPru, sorry for the confusion but a big thanks for your support!!!
> 
> what web server you mean?

The integrated web server in your heat pump. If you open the pi address your heat pump in any browser, you can also control your heat pump.

My Webserver hangs up. If you see just a loading screen without a field to enter pin, your Webserver hangs up, too.

So I restarted my heat pump. After restart, all is working now.

**Comment by BenPru** [comment]
Yes, I have the same about two years ago. After firmware upgrade the network config could be wrong. It is known by AIT...
Please check your network config after every firmware upgrade. Perhaps you can also check it with a mobile app e.g. Luxprobe.
---
I will create a new version with own error handling in the config flow.

**Comment by BenPru** [comment]
I think I can produce it or something like this. If I use Port 80 for the connection, the connection seems to be valid but the returned data responses in the length calculation a very high length. In the data processing the loop runs very, very long and ha run in a timeout. I add a max data length or a timeout. But this is in the code of the underlying Bouni\Luxtronik module.

**Comment by idominiki** [comment]
Hey @BenPru 

Version 2023.10.9 is working for me.
![Bildschirmfoto 2023-10-10 um 19 17 16](https://github.com/BenPru/luxtronik/assets/62521486/eb0a33c6-a48b-4530-b5ed-be31aa51301f)

Version 2023.10.10 can't load the integration and home assistant is restarting directly after start.
![Bildschirmfoto 2023-10-10 um 07 05 40](https://github.com/BenPru/luxtronik/assets/62521486/d3e969a4-45d5-496c-8a43-b88cb64156e9)

**Comment by BenPru** [comment]
> Version 2023.10.10 can't load the integration and home assistant is restarting directly after start.

I have changed some params in the main branch to test:
* Rollback socket_close result True>False in error case
* Increase socket timeout 10>100
* Increase max data length

Please test the main branch and give feedback.

**Comment by idominiki** [comment]
> > Version 2023.10.10 can't load the integration and home assistant is restarting directly after start.
> 
> I have changed some params in the main branch to test:
> 
> * Rollback socket_close result True>False in error case
> * Increase socket timeout 10>100
> * Increase max data length
> 
> Please test the main branch and give feedback.

Changes doesn't help. Home Assistant startup is much slower / unresponsive. Many integrations has status "initializing".
<img width="356" alt="image" src="https://github.com/BenPru/luxtronik/assets/62521486/98712c53-8e6e-43e1-9636-ad9e198029d8">

**Comment by BenPru** [comment]
Please try [2023.10.11-Beta](https://github.com/BenPru/luxtronik/releases/tag/2023.10.11-Beta) and check that all is fixed finally.
Thank you for your input and tests.

**Comment by idominiki** [comment]
> Please try [2023.10.11-Beta](https://github.com/BenPru/luxtronik/releases/tag/2023.10.11-Beta) and check that all is fixed finally. Thank you for your input and tests.

Sadly no: Errors during setup. But Home Assistant is starting normally. Reloading Integration doesn't fix.

<img width="701" alt="image" src="https://github.com/BenPru/luxtronik/assets/62521486/06cac568-b8ec-4898-ab17-c076e079678d">
<img width="815" alt="image" src="https://github.com/BenPru/luxtronik/assets/62521486/f5145187-e7a7-41df-85f6-b0244d924fcd">

**Comment by idominiki** [comment]
> Please try [2023.10.11-Beta](https://github.com/BenPru/luxtronik/releases/tag/2023.10.11-Beta) and check that all is fixed finally.
> 
> Thank you for your input and tests.

v2023.10.12-beta works flawlessly. 

Thank you for your work!!

**Comment by rhammen** [comment]
> > Please try [2023.10.11-Beta](https://github.com/BenPru/luxtronik/releases/tag/2023.10.11-Beta) and check that all is fixed finally.
> > Thank you for your input and tests.
> 
> v2023.10.12-beta load the integration but two devices can't be setup. 

See #149 , will be fixed with #150

**Comment by ondras76** [comment]
Just let you know, I was try new release 2023.10.13 and stil the same, about my problem with the cloud, can't connect to the cloud.

**Comment by BenPru** [comment]
> @BenPru Just let you know, I was try new release 2023.10.13 and stil the same, about my problem with the cloud, can't connect to the cloud. log whe I try connect the cloud, just say againg, is it clean HAos with just Luxtronik integration.

Please try the new timeout config values.

**Comment by ondras76** [comment]
> > @BenPru Just let you know, I was try new release 2023.10.13 and stil the same, about my problem with the cloud, can't connect to the cloud. log whe I try connect the cloud, just say againg, is it clean HAos with just Luxtronik integration.
> 
> Please try the new timeout config values.

Can you tell me how much and direction.

**Comment by BenPru** [comment]
@ondras76 Please test different timeouts and package lengths for your case:
![image](https://github.com/BenPru/luxtronik/assets/32298537/bf79fa28-7592-4e6f-9831-713df95ffbe0)

At the moment we have no stable release for HA>=2023.9.*.
I would like to release a stable version.
The other response is that it is now running for all others. Only in your case it isn't and I can not see any luxtronik errors in your log.

**Comment by ludeeus** [comment]
> HA Cloud and the log entries have nothing to do with the Luxtronik integration.

Took a quick look at the code, because of several reports of this now.
Because this part <https://github.com/BenPru/luxtronik/blob/576736e5c92cbce5f47d3523766f821e706bde8f/custom_components/luxtronik/base.py#L91> sets an invalid code for the entire runtime (all of HA and its integrations) it is the cause of that log entry (and failure).

**Comment by BenPru** [comment]
> sets an invalid code for the entire runtime (all of HA and its integrations) it is the cause of that log entry (and failure).

Okay, thank you very much for this hint. Small adjustment with a big impact...
I use the internal translation only for the evu text. And since HA 2023.07.* the translation of attribute names and states is available in core.
I now try to replace my internal translation with new state attributes.

**Comment by BenPru** [comment]
Please try the latest prerelease: [2023.10.20-Alpha](https://github.com/BenPru/luxtronik/releases/tag/2023.10.20-Alpha)

**Comment by ondras76** [comment]
2023.10.20-Alpha looks OK! No problem for first 15min. Thank you so much for solving this problem. You made my day! 

This only one log issue, I don't know what that mean, but cloud working again.

"Logger: py.warnings
Source: helpers/update_coordinator.py:172
First occurred: 10:39:52 AM (2 occurrences)
Last logged: 10:40:53 AM

/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py:172: RuntimeWarning: coroutine 'LuxtronikCoordinator.write' was never awaited update_callback()"

**Comment by BenPru** [comment]
> 2023.10.20-Alpha looks OK! 

Great. Thanks for your response.
I close this issue now. If the problem still exists feel free to reopen.
