### ISSUE TITLE
sensor.luxtronik2_status broke

### ISSUE THREAD

**Issue by qubabos** [BenPru/luxtronik#41]
You broke sensor.luxtronik2_status with latest update 2022.11.28. My heat pump works from latest 9h but sensor shows no request.  Using it with alpha Innotec. Could you be more carefull in future updates and do not brake something that already works just fine?

**Comment by BenPru** [comment]
In your case please have a look in the attribute "Status raw" from sensor.luxtronik2_status, sensor.luxtronik2_status_line_1 and sensor.luxtronik2_status_line_3. Please tell it in this ticket.

**Comment by qubabos** [comment]
![2022-11-30_063231](https://user-images.githubusercontent.com/2496350/204715652-111b2606-9424-4b74-a0c4-a0cf005f8cc7.png)
![2022-11-30_063438](https://user-images.githubusercontent.com/2496350/204715902-05b3a105-0765-4234-ba81-79238b9f6621.png)
since update it shows always "Idle (no request)" but there was a heating and domestic water programs runned in the meantime

**Comment by Taijian** [comment]
I also have this issue: sensor.luxtronik2_status no longer updates, even though the actual status of the HP does change (between idle, heating and water). This also started happening after the latest update.

**Comment by BenPru** [comment]
@qubabos @Taijian 
Thanks for your response. I think I have found a nullpointer in the evu text calculation for heatpumps without evu.
Please try the last prerelease [2022.11.30](https://github.com/BenPru/luxtronik/releases/tag/2022.11.30).
I have marked 2022.11.28 and 2022.11.30 as prerelease so we can test it before we launch this as default.

**Comment by qubabos** [comment]
How to install prerelease?

**Comment by BenPru** [comment]
> How to install prerelease?

I think you can activate "Enable experimental features" under Devices => HACS "configure".

**Comment by qubabos** [comment]
> > How to install prerelease?
> 
> I think you can activate "Enable experimental features" under Devices => HACS "configure".

This option completly stops Hacs integrations. Any manual install available?

**Comment by Kars-de-Jong** [comment]
On my Alpha Innotec those status lines 1 - 3 always show those same texts too, and the status time is always 0.

**Comment by qubabos** [comment]
> 

maybe we can split [Kars-de-Jong](https://github.com/Kars-de-Jong) post into seperate issue and deal with Alpha Innotec support ?

**Comment by Crashman1983** [comment]
just checked prelease 11/30 --> Status working again

**Comment by qubabos** [comment]
Can we turn prerelease into release ? Can't resolve testing prereleases issue.

**Comment by BenPru** [comment]
@qubabos 

> Any manual install available?

See [readme section 1b](https://github.com/BenPru/luxtronik/tree/main#1b-install-manually).

**Comment by BenPru** [comment]
I hope the current release [2022.12.01](https://github.com/BenPru/luxtronik/releases/tag/2022.12.01) should fix this.
Sorry for the trouble.

**Comment by qubabos** [comment]
> I hope the current release [2022.12.01](https://github.com/BenPru/luxtronik/releases/tag/2022.12.01) should fix this. Sorry for the trouble.

Thanks a lot, waiting for this but hacs doesn't see any new update.

**Comment by qubabos** [comment]
> I hope the current release [2022.12.01](https://github.com/BenPru/luxtronik/releases/tag/2022.12.01) should fix this. Sorry for the trouble.

It doesnt fix it. Right now my HP works on domestic water but sensor shows heating.

**Comment by qubabos** [comment]
How to obtain those logs?

**Comment by BenPru** [comment]
> How to obtain those logs?

Settings => System => Logs
Search logs = luxtronik
Copy Errors in this ticket.

**Comment by Taijian** [comment]
> I hope the current release [2022.12.01](https://github.com/BenPru/luxtronik/releases/tag/2022.12.01) should fix this. Sorry for the trouble.

I can confirm that 2022.12.01 does fix my issue: Heatpump status is one again logged and displayed correctly.

**Comment by augi** [comment]
Works well for me too.

**Comment by qubabos** [comment]
> > 2022.12.01 doesnt fix it. Right now my HP works on domestic water but sensor shows heating.
> 
> Can you check and provide your logfile? Do you get an error message in the log?

`Logger: homeassistant
Source: custom_components/luxtronik/sensor.py:888
Integration: luxtronik
First occurred: December 1, 2022 at 21:10:41 (1131 occurrences)
Last logged: 06:32:21

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 813, in _update_entity_states
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 532, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 586, in _async_write_ha_state
    attr.update(self.extra_state_attributes or {})
  File "/config/custom_components/luxtronik/sensor.py", line 926, in extra_state_attributes
    ATTR_STATUS_TEXT: self._build_status_text(),
  File "/config/custom_components/luxtronik/sensor.py", line 888, in _build_status_text
    elif evu_event_minutes <= 30:
TypeError: '<=' not supported between instances of 'NoneType' and 'int'

`

**Comment by qubabos** [comment]
after completly remove and adding integration from scratch - it works fine. thanks a lot for this. can be marked as resolved.
