### ISSUE TITLE
Error while reading custom sensors

### ISSUE THREAD

**Issue by ElBart00** [BenPru/luxtronik#52]
Logger: homeassistant.components.sensor
Source: custom_components/luxtronik2/sensor.py:435
Integration: Sensor ([documentation](https://www.home-assistant.io/integrations/sensor), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22))
First occurred: 06:38:25 (1 occurrences)
Last logged: 06:38:25

Error while setting up luxtronik2 platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 281, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/luxtronik2/sensor.py", line 435, in async_setup_entry
    if luxtronik.get_value("parameters.ID_Waermemenge_ZWE") > 0:
TypeError: '>' not supported between instances of 'NoneType' and 'int'

**Comment by BenPru** [comment]
Please try the current pre-release [2012.12.16a](https://github.com/BenPru/luxtronik/releases/tag/2012.12.16a)

**Comment by ElBart00** [comment]
I've installed 2012.12.17 and this issue is solved. Thanks.

**Comment by compies** [comment]
Problem persists in current 2023.02.02 Release:

2023-04-28 10:33:08.113 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up luxtronik2 platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 304, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/luxtronik2/sensor.py", line 530, in async_setup_entry
    add_sensor_if_active(luxtronik, entities, "visibilities.ID_Visi_Waermemenge_ZWE", LuxtronikSensor(
  File "/config/custom_components/luxtronik2/sensor.py", line 1193, in add_sensor_if_active
    if luxtronik.get_value(check_key) <= 0:
TypeError: '<=' not supported between instances of 'NoneType' and 'int'
